version: 2.1

jobs:
  build:
    docker:
      - image: docker:19.03.12

    steps:
      - checkout

      # Login to Docker Hub
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Build and tag Docker image
      - run:
          name: Build and tag Docker image
          command: |
            docker build -t $DOCKER_USERNAME/your-image-name .
            docker tag $DOCKER_USERNAME/your-image-name $DOCKER_USERNAME/your-image-name:latest

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: docker push $DOCKER_USERNAME/your-image-name

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
